export const STICKERS = [
  { emoji: '✨', name: 'Sparkles' },
  { emoji: '💀', name: 'Skull' },
  { emoji: '💔', name: 'Broken Heart' },
  { emoji: '☠️', name: 'Skull Cross' },
  { emoji: '🔴', name: 'Red Circle' },
  { emoji: '💙', name: 'Blue Heart' },
  { emoji: '💜', name: 'Purple Heart' },
  { emoji: '⚡', name: 'Lightning' },
  { emoji: '🌙', name: 'Moon' },
  { emoji: '⭐', name: 'Star' },
  { emoji: '🕷️', name: 'Spider' },
  { emoji: '🔱', name: 'Cross' },
  { emoji: '🔮', name: 'Crystal' },
  { emoji: '🎭', name: 'Mask' },
  { emoji: '🐉', name: 'Dragon' },
  { emoji: '🧠', name: 'Brain' },
  { emoji: '💾', name: 'Disk' },
  { emoji: '💻', name: 'Computer' },
  { emoji: '📷', name: 'Camera' },
  { emoji: '🎧', name: 'Headphones' },
  { emoji: '💎', name: 'Diamond' },
  { emoji: '🔪', name: 'Knife' },
  { emoji: '🌀', name: 'Cyclone' },
  { emoji: '⚔️', name: 'Swords' },
]
